services:
  db:
    image: $IMAGE_DB
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "8002:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      retries: 5
      start_period: 5s
      timeout: 2s

  backend:
    image: $IMAGE_BACKEND
    ports:
      - "8001:80"
    links:
      - "db:database"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?sslmode=disable
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost/health || exit 1"]
      interval: 2s
      retries: 5
      start_period: 5s
      timeout: 2s
    depends_on:
      db:
        condition: service_healthy
        restart: true

  frontend:
    image: $IMAGE_FRONTEND
    ports:
      - "8000:80"
    links:
      - "backend:backend"
    environment:
      API_BASE: http://backend
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 2s
      retries: 5
      start_period: 5s
      timeout: 2s
    depends_on:
      backend:
        condition: service_healthy
        restart: true

volumes:
  db-data:
